### PR TITLE
[PLT-7389] Make vm.max_map_count more robust for Elasticsearch

### PR DESCRIPTION
**Pull request by cpanato**
Jira: https://mattermost.atlassian.net/browse/PLT-7389
GitHub: https://github.com/mattermost/mattermost-server/issues/7332

### CODE REVIEW

**Comment by cpanato** [comment]
@grundleborg yep you right, will remove that.

**Comment by grundleborg** [comment]
@cpanato apologies, posted this comment in the other PR by mistake - I actually meant to post it here:

I tried running this branch and it didn't work:

```
╰─$ make install
helm install dist/mattermost-helm*.*
Error: release singed-bronco failed: DaemonSet.apps "singed-bronco-mattermost-elasticsearch-ds" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"name":"singed-bronco-mattermost-elasticsearch-ds"}: `selector` does not match template `labels`
Makefile:34: recipe for target 'install' failed
make: *** [install] Error 1
```

Any ideas what's up?

**Comment by cpanato** [comment]
@grundleborg I made a fix, I guess 😄  the label name was wrong in one part. can you please try again?

**Comment by grundleborg** [comment]
Tested and verified this is working. Thanks @cpanato

**Comment by cpanato** [comment]
that's cool!! thanks!!!

**Comment by grundleborg** [comment]
@coreyhulen @crspeller please can one of you guys do a second review on this when you have a moment? I'd really like to get this merged.

**Pull request merged**
