### PR TITLE
remove nginx-ingress and kube-lego

### PR DESCRIPTION
**Pull request by cpanato**
This is part of the k8s cluster configuration and the user can select
other ingress.

### CODE REVIEW

**Comment by pgold30** [comment]
Tried this, the ingress and kube lego are being generated anyway

**Comment by cpanato** [comment]
@pgold30 did you run `helm dependency update` and then delete the .tar.gz files in the charts folder?

**Comment by pgold30** [comment]
Yes, and also try from scratch, i was able to remove nginx and kube-lego installation settings ingress values to false, it seems that for some reason when ingress is on true nginx and kube-lego are deployed

**Comment by cpanato** [comment]
@pgold30 I retest locally and it did not install the ngnix-ingress and kubelego using the default config

**Comment by cpanato** [comment]
will add 😄

**Comment by cpanato** [comment]
@jwilander @crspeller update the readme

**Comment by cpanato** [comment]
@crspeller @jwilander ptal

**Comment by jwilander** [comment]
@cpanato this means that ltops w/ k8s will also need `nginx-ingress` as a prerequisite. Maybe we should add to the ltops tool some code to check if it's installed already and if it's not, have it install `nginx-ingress`

**Comment by cpanato** [comment]
@jwilander I dont think the ltops need the nginx ingress, because all the load we make is intra cluster usinf the cluster dns and not required an external endpoint.

**Comment by jwilander** [comment]
We do want to be able to access the cluster externally if needed though

**Comment by jwilander** [comment]
Chatted with @cpanato, right now the load test pods are pointed directly at the app servers so they don't need the ingress. We're going to create a ticket to point them at the ingress (for image caching, and because that's how real set ups will work) and create nginx ingress with ltops if needed

**Pull request merged**
