### PR TITLE
Improve config.tpl, several config values added

### PR DESCRIPTION
**Pull request by pgold30**
Added the following values to config.tpl to enable more config options, some are really important like email settings
"EnableGifPicker": {{ .Values.global.features.enableGifPicker.enabled }},
"SiteName": {{ .Values.global.siteName }},
"EnableTeamCreation": {{ .Values.global.features.teamCreation.enabled }},
"EnableOpenServer": {{ .Values.global.openServer.enabled }},
"RestrictCreationToDomains": {{ .Values.global.features.restrictCreationtoDomains }},
"EnableCustomBrand": {{ .Values.global.enableCustonBrand.enabled }},
"CustomBrandText": {{ .Values.global.customBrandText }},
"CustomDescriptionText": {{ .Values.global.customBrandDescriptionText }},
"MinimumLength": {{ .Values.global.passwordLength }},
"EnableFileAttachments": {{ .Values.global.features.enableFileAttachment.enabled }},
"EnableSignUpWithEmail": {{ .Values.emailSettings.enableSignUpWithEmail.enabled }},
"SendEmailNotifications": {{ .Values.emailSettings.sendEmailNotifications.enabled }},
"RequireEmailVerification": {{ .Values.emailSettings.requireEmailVerification.enabled }},                  
"FeedbackName": {{ .Values.emailSettings.feedbackName }},
"FeedbackEmail": {{ .Values.emailSettings.feedbackEmail }},
"FeedbackOrganization": {{ .Values.emailSettings.feedbackOrganization }},
"SMTPUsername": {{ .Values.emailSettings.SMTPUsername }},
"SMTPPassword": {{ .Values.emailSettings.SMTPPassword }},
"SMTPServer": {{ .Values.emailSettings.SMTPServer }},
"SMTPPort": {{ .Values.emailSettings.SMTPPort }},
"ConnectionSecurity": {{ .Values.emailSettings.connectionSecurity }},

### CODE REVIEW

**Comment by pgold30** [comment]
@cpanato  I see, do you have an estimated date for that, may i help you with something?

**Comment by crspeller** [comment]
@cpanato Can't we take this then merge it into ours?

**Comment by cpanato** [comment]
Yes off course. I will check the build failure.

**Comment by pgold30** [comment]
@cpanato thanks for your guidelines , i will made the changes requested tomorrow.

**Comment by pgold30** [comment]
I see that you applied the changes! will close this, sry for not following up was traveling, im in berlin now

**Pull request closed without merging**
