### PR TITLE
[PLT-7388] Add persistent volume claims to Elasticsearch

### PR DESCRIPTION
**Pull request by cpanato**
Jira Ticket: https://mattermost.atlassian.net/browse/PLT-7388
GitHub: https://github.com/mattermost/mattermost-server/issues/7330

### CODE REVIEW

**Comment by cpanato** [comment]
humm, good question, will look into and update if need. thanks @grundleborg

**Comment by grundleborg** [comment]
@cpanato did you ever figure out whether the `master` and `client` nodes needed PVCs or not?

**Comment by cpanato** [comment]
@grundleborg don't need the client. I will update that.

**Comment by grundleborg** [comment]
Also, I tried running this branch and it didn't work:

```
╰─$ make install
helm install dist/mattermost-helm*.*
Error: release singed-bronco failed: DaemonSet.apps "singed-bronco-mattermost-elasticsearch-ds" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"name":"singed-bronco-mattermost-elasticsearch-ds"}: `selector` does not match template `labels`
Makefile:34: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by cpanato** [comment]
rebased and fixed the conflict

**Pull request merged**
